import './MethodologyPage.css'

/**
 * Full-screen overlay explaining CosmiDex's data sources, architecture, habitability
 * scoring methodology, known data limitations, and AI-generated content disclosure.
 *
 * @param props
 * @param props.onClose - Called when the user dismisses the overlay.
 * @returns The methodology overlay panel.
 */
export default function MethodologyPage({ onClose }) {
  return (
    <div className="methodology-overlay">
      <div className="methodology-panel">
        <button className="methodology-close" onClick={onClose} aria-label="Close">×</button>

        <h1>Methodology &amp; Sources</h1>

        <section>
          <h2>Author</h2>
          <h3>Zac Cheatle</h3>
          <p>
            {' '}
            <a href="https://github.com/zaccheatle/cosmidex" target="_blank" rel="noreferrer">
              Cosmidex Github Repository
            </a>{' '} |
            {' '}
            <a href="https://www.linkedin.com/in/zaccheatle/" target="_blank" rel="noreferrer">
              LinkedIn
            </a>{' '}
          </p>
        </section>

        <section>
          <h2>Architecture</h2>
          <p>
            ELT data pipelines orchestrated via Dagster extract data from source → validate → load into Postgres →
            transform through dbt (Bronze/Silver/Gold layers) → served by a FastAPI backend to a
            React frontend hosted in AWS.
          </p>
        </section>

        <section>
          <h2>Data Sources</h2>
          <h3>Exoplanets</h3>
          <p>
            Exoplanet data comes from NASA's{' '}
            <a href="https://exoplanetarchive.ipac.caltech.edu/" target="_blank" rel="noreferrer">
              Exoplanet Archive
            </a>{' '}
            (PSCompPars — Planetary Systems Composite Parameters table), pulled via its TAP service.
            As of the last refresh, the archive lists 6,324 confirmed exoplanets; CosmiDex currently
            displays the 75 that fall into Tier 1, 2, or 3 of our habitability classification below.
          </p>
        </section>

        <section>
          <h2>Habitability Scoring</h2>
          <p>
            <strong>Earth Similarity Index (ESI)</strong> is a weighted product of how closely a
            planet's radius, density, escape velocity, and equilibrium temperature match Earth's —
            temperature is weighted most heavily. 1.0 = identical to Earth, 0 = completely alien.
          </p>
          <p>
            <strong>Habitable Zone Distance (HZD)</strong> measures where a planet sits within its
            star's habitable zone: <code>(2 × orbital distance − hz_inner − hz_outer) / (hz_outer − hz_inner)</code>.
            0 = center of the zone, ±1 = the inner/outer edge.
          </p>
          <p>
            <strong>Tiers</strong> — Tier 1: ESI ≥ 0.8, in the conservative habitable zone, rocky
            composition, low orbital eccentricity, orbits an F/G/K star. Tier 2: ESI ≥ 0.6, in the
            habitable zone, rocky. Tier 3: in the habitable zone only, regardless of size or
            composition. Everything else is Non-Habitable.
          </p>
        </section>

        <section>
          <h2>Known Limitations</h2>
          <ul>
            <li>
              Surface temperature is estimated from stellar flux and distance, not measured — actual
              conditions (atmosphere, greenhouse effect, weather) are unknown for nearly all of these
              planets.
            </li>
            <li>
              An orbital eccentricity of exactly 0 sometimes means the orbit was assumed circular
              during fitting due to limited observational data, rather than confirmed as circular.
            </li>
            <li>
              Composition (Rock/Iron, Rock/Silicate, Water/Ice, Ice Giant, Gas Giant) is inferred from
              density alone — a coarse classification, not a direct measurement.
            </li>
          </ul>
        </section>

        <section>
          <h2>AI-Generated Content</h2>
          <p>
            Planet illustrations and the size-comparison-vs-Earth images are generated by Google's
            Gemini image model, prompted using only real measured/derived fields already in the data
            (composition category, radius ratio, star spectral type) — no invented terrain, weather,
            or geology, since the underlying dataset doesn't include that. Planet descriptions are
            generated by Google's Gemini model from the same underlying stats. Both are marked with an
            "AI-generated" note wherever they appear.
          </p>
        </section>
      </div>
    </div>
  )
}
