name: API CI
on:
    pull_request:
        paths: 
            - cosmidex_api/**
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: "3.14"
            - uses: astral-sh/ruff-action@v3
              with:
                src: cosmidex_api
            - uses: astral-sh/ruff-action@v3
              with:
                args: format --check
                src: cosmidex_api